name: Node tests

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  versions:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    outputs:
      nodeVersion: ${{ steps.versions.outputs.nodeVersion }}
      npmVersion: ${{ steps.versions.outputs.npmVersion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^7'

  test:
    runs-on: ubuntu-latest
    needs: versions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node ${{ needs.versions.outputs.nodeVersion }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ needs.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ needs.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ needs.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Test and process coverage
        run: npm run test:coverage
  
      - name: Collect coverage
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          files: ./coverage/lcov.info

  jsunit:
    runs-on: ubuntu-latest
    needs: versions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node ${{ needs.versions.outputs.nodeVersion }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ needs.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ needs.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ needs.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:jsunit

  handlebars:
    runs-on: ubuntu-latest
    needs: versions

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node ${{ needs.versions.outputs.nodeVersion }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ needs.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ needs.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ needs.versions.outputs.npmVersion }}"

      - name: Install dependencies
        run: npm ci

      - name: Run compile
        run: ./build/compile-handlebars-templates.sh
